### ISSUE TITLE
HashFile fails to get() some keys that were added and are contained in the HashFile.elements() set

### ISSUE THREAD

**Issue by stevenschlansker** [sunnygleason/g414-hash#11]
Hi again,
I've come to bother you with what I presume is another bug :-)

https://github.com/stevenschlansker/g414-stress-test

I did not submit this one as a patch since the test dataset is 15MB compressed, feel free to take any or all of the repo that you like and use it as you please (including integrating it into the core if you think it is a good regression test)

Short version:
For 600K keys, the HashFile contains some data that cannot be fetched yet shows up via the iterator.  About 40k keys are affected with the test data set.

I've included a bonus test showing that HashFile2 does not have this problem.

The test data is a scrubbed version of my production data, which is how I noticed this problem.

**Comment by stevenschlansker** [comment]
Interesting.  Seems that the insertion order can matter here, as the same data succeeds just fine in some permutations of the data but fails others.

**Comment by sunnygleason** [comment]
Found & fixed the position offset bug in HF1 -- please feel free to give it a try & let me know what you find! I'll definitely work a minimal test case in based on your example soon. I think it's triggered by elements with larger total key + data sizes than 2k.

**Comment by sunnygleason** [comment]
fixed in 0.7.3

**Comment by sunnygleason** [comment]
Cool, I think we made it past the bug verification stage, I'll close this issue as fixed - thanks for using g414-hash!
