### ISSUE TITLE
Specify encoding in String.getBytes() method (for hashing)

### ISSUE THREAD

**Issue by cowtowncoder** [sunnygleason/g414-hash#3]
There are couple of places where Strings are converted to byte[] without specifying encoding.
This is risky, since default is to use platform-specific default encoding, which varies from system to system (typically it's either Latin-1 or UTF-8; nowadays more commonly UTF-8).
It would probably make most sense to just use UTF-8; if caller wants other encoding, she can just get bytes explicitly, calc hash on byte array.

**Comment by sunnygleason** [comment]
fixed in 0.3.0 release
