### ISSUE TITLE
Add 32-bit hash versions?

### ISSUE THREAD

**Issue by cowtowncoder** [sunnygleason/g414-hash#5]
Given that time to produce 64-bit hashes is probably not much less than equivalent for producing 2 32-int hashes, it would be useful to also have 32-bit versions. Specific use case is that of building Bloom filters, where number of bits needed is variable; so when, say, 80 bits are needed (8 hash functions over 1024 bit mask), it would be enough to calculate 3 32-bit hashes instead of 2 64-bit hashes.

**Comment by sunnygleason** [comment]
YES! This is a great idea. Any thoughts on how to introduce 32-bit into the interface? Let's work this into the 0.5.0 release coming up soon...

**Comment by sunnygleason** [comment]
I just thought of something, should we have something like Hash.fill(byte[]), which just iterates over byte[] filling in 32 or 64-bit chunks as well?

**Comment by cowtowncoder** [comment]
Yes that could work. Or maybe even an abstraction for N bits of hash code, and simple iterator over it (give me next N hash bits)? That's what bloom filter could use.

**Comment by sunnygleason** [comment]
checked into master ... ready for the 0.5.0 release!

**Comment by cowtowncoder** [comment]
Great!
